idf_component_register(SRCS "ferry.c"
                            "ble_hid.c"
                            "cursor.c"
                            "kvm.c"
                            "layout.c"
                            "our_descriptor.c"
                            "usb_input.c"
                       INCLUDE_DIRS ".")
